#!/bin/bash
################################
# Author: ekazyam
# Data  : 2017/02/12
# Ver   : 1.0.1
################################
# for chaberi user count.
# Setting threshold value for warn and critical.
WARN='200'
CRITICAL='300'

# Setting URL.
URL='http://www.chaberi.com/'

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

	# glaph common
        echo 'graph_title chaberi'
        echo 'graph_args -l 0 '
        echo 'graph_vlabel C'
        echo 'graph_category system'

	# usercount data
        echo 'users.label users'
        echo 'users.draw LINE'
	echo "users.warning ${WARN}"
	echo "users.critical ${CRITICAL}"

        print_warning users
        print_critical users

        exit 0
fi

USER_COUNT=`curl -s ${URL} | grep -E "暇つぶし! 現在[[:digit:]]*人チャット中" -o | grep -E "[[:digit:]]*" -o`

echo "users.value ${USER_COUNT}"

