#!/usr/bin/php
<?php
/*##############################
* Author: Rum Coke
* Data  : 2015/06/17
* Ver   : 0.9.0
*##############################*/
/* include create graph lib */
require_once('/usr/share/munin/plugins/lib_php/munin_graph.php');
require_once('/usr/share/munin/plugins/lib_php/munin_cpu_temp.php');
/*******************
 * User Count.
 *******************/
/* SetCpuTemp. */
$cpu_temp = new CpuTemp();
$label = array(
 'liva'
);

/* Exec httping. */
$cpu_temp->measureTemp();

/*******************
 * Graph Create.
 *******************/
/* SetGraphData */
$graph = new CreateGraph();
$graph->setWarn('50.0');
$graph->setCritical('60.0');
$graph->setTitle('Cpu Temperature by PHP');
$graph->setVlabel('Temp');
$graph->setCategory('mytool');
$graph->setScale('yes');
$graph->setFormat('%6.2lf');
$graph->setDraw('LINE1');
$graph->setInfo('CPU Temperature.');
$graph->setLabel($label);
$graph->setValue($cpu_temp->getResult());

/* Arg Check at this function. */
if( isset($argv[1]))
{
	if ( "$argv[1]" == "autoconf" )
	{
		$graph->PrintData('yes');
	       	exit;
	}

	if ( "$argv[1]" == "config" )
	{
		/* show parameter */
		$graph->showParameters();
		exit;
	}
}

/* Show Value and Create Graph. */
$graph->showValue();

exit;
?>
