#!/bin/bash
################################
# Author: Rum Coke
# Data  : 2015/05/17
# Ver   : 0.9.1
################################
# Send to HttpPing to URLs.
function SendHttpPing()
{
	ArrayResult=`httping -c ${TRY} ${URL} 2> /dev/null`
	echo ${ArrayResult} | grep "${ERROR}"  && ArrayResult=''
}

# Check HttpPing Response.
function CheckHttpResponse()
{
		if [ -n "${ArrayResult}" ]
		then
			WORK=`echo ${ArrayResult} | sed -e 's/.*round-trip\ min\/avg\/max\ =\ //g' -e 's/\ ms$//g'`
			Avg=`echo ${WORK} | awk -F\/ '{ print $2 }'`
			Min=`echo ${WORK} | awk -F\/ '{ print $1 }'`
			Max=`echo ${WORK} | awk -F\/ '{ print $3 }'`
		fi	
}

################################
# Main Function
################################

# Locale Setting.
LANG=C

# Try Count.
TRY=3

# Warn and Critical.(ms)
WARN_RES='1000.0'
CRITICAL_RES='5000.0'

# Error Msg.
ERROR='No valid IPv4 or IPv6 address found for'

# URLs.
URL="http://www.google.co.jp/"

# Label for URLs.
URL_LABEL=( "Min" "Avg" "Max")

# Exec httping.
SendHttpPing

# Response Check.
CheckHttpResponse

if [ "$1" = "autoconf" ]; then
	echo yes
       	exit 0
fi

if [ "$1" = "config" ]; then
	# Glaph Common
	echo 'graph_title Http Ping Specific'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel response(ms)'
	echo 'graph_category network'
	echo 'graph_scale yes'
	echo 'graph_printf %6.2lf'
	echo "graph_order ${URL_LABEL[2]} ${URL_LABEL[1]} ${URL_LABEL[0]}"

	# Set Info.
	for (( Z = 0; Z < ${#URL_LABEL[@]}; ++Z ))
	do
		echo "${URL_LABEL[$Z]}.label ${URL_LABEL[$Z]}"
		echo "${URL_LABEL[$Z]}.draw AREA"
		echo "${URL_LABEL[$Z]}.warning ${WARN_RES}"
		echo "${URL_LABEL[$Z]}.critical ${CRITICAL_RES}"
		echo "${URL_LABEL[$Z]}.info Http Response."
	done

	exit 0
fi

# Set Value.
echo "${URL_LABEL[0]}.value ${Min}"
echo "${URL_LABEL[1]}.value ${Avg}"
echo "${URL_LABEL[2]}.value ${Max}"

