#!/bin/bash
################################
# Author: Rum Coke
# Data  : 2015/05/06
# Ver   : 1.4.0
################################
# for EL-USB-RT

# path of tempsensor binary
BIN_PATH="/usr/local/bin"

# Setting threshold value for warn and critical.
WARN_TEMP='30'
CRITICAL_TEMP='35'

WARN_HYD='40:'
CRITICAL_HYD='30:'

WARN_DISCOMFORT='75'
CRITICAL_DISCOMFORT='80'

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

	# glaph common
        echo 'graph_title room_temperature/himidity'
        echo 'graph_args -l 0 '
        echo 'graph_vlabel Temp/Himid'
        echo 'graph_category system'

	# temp data
        echo 'temperature.label temperature'
        echo 'temperature.draw LINE'
	echo "temperature.warning ${WARN_TEMP}"
	echo "temperature.critical ${CRITICAL_TEMP}"

	# himidity data
        echo 'himidity.label himidity'
        echo 'himidity.draw LINE'
	echo "himidity.warning ${WARN_HYD}"
	echo "himidity.critical ${CRITICAL_HYD}"

	# discomfort index data
        echo 'discomfort.label discomfort index'
        echo 'discomfort.draw LINE'
	echo "discomfort.warning ${WARN_DISCOMFORT}"
	echo "discomfort.critical ${CRITICAL_DISCOMFORT}"

        print_warning temperature
        print_critical temperature

        print_warning himidity
        print_critical himidity

        print_warning discomfort
        print_critical discomfort

        exit 0
fi

work=`${BIN_PATH}/tempsensor -s`

ROOM_TEMP=`echo ${work} | awk -F',' '{print $1}'`
ROOM_HYD=`echo ${work} | awk -F',' '{print $2}'`
ROOM_RELUX=`echo "scale=2; 0.81*$ROOM_TEMP+0.01*$ROOM_HYD*(0.99*$ROOM_TEMP-14.3)+46.3" | bc | cut -d "." -f 1`

echo "temperature.value ${ROOM_TEMP}"
echo "himidity.value ${ROOM_HYD}"
echo "discomfort.value ${ROOM_RELUX}"

