#!/bin/bash
################################
# Author: Rum Coke
# Data  : 2015/05/19
# Ver   : 0.9.3
################################
# Set ESSID
function SetEssid()
{
	ArrayResult=(`/sbin/iwlist wlan0 scan | egrep -o '(Quality=[[:digit:]]{1,3}\/[[:digit:]]{2,3}|ESSID:.*)'`)
}

# Check Signals.
function CheckSignals()
{
	I=0
	if [ `echo ${ArrayResult[0]} | egrep '^ESSID:'` ]
	then
		while (( Z < ${#ArrayResult[@]} ))
		do
			if [ ! `echo ${ArrayResult[$Z]} | egrep '(\x00)+'` ] && [ `echo ${ArrayResult[$Z]} | sed -r 's/(ESSID:|")//g'` ]
			then
				LABEL[$I]=`echo ${ArrayResult[$Z]} | sed -r 's/(ESSID:|")//g'`
				SIGNAL[$I]=`echo ${ArrayResult[$(($Z+1))]} | sed -r 's/(Quality=|\/[[:digit:]]{2,3})//g'`
				I=$(($I+1))
			fi
			Z=$(($Z+2))
		done

	else
		while (( Z < ${#ArrayResult[@]} ))
		do
			if [ ! `echo ${ArrayResult[$((Z+1))]} | egrep '(\x00)+'` ]
			then
				LABEL[$I]=`echo ${ArrayResult[$(($Z+1))]} | sed -r 's/(ESSID:|")//g'`
				SIGNAL[$I]=`echo ${ArrayResult[$Z]} | sed -r 's/(Quality=|\/[[:digit:]]{2,3})//g'`
				I=$(($I+1))
			fi
			Z=$(($Z+2))
		done
	fi
}

################################
# Main Function
################################
# Locale Setting.
LANG=C

# Warn and Critical.(ms)
WARN_RES='30.0:'
CRITICAL_RES='10.0:'

# Exec iwlist.
SetEssid

# Signal Check.
CheckSignals

if [ "$1" = "autoconf" ]; then
	echo yes
       	exit 0
fi

if [ "$1" = "config" ]; then
	# Glaph Common
	echo 'graph_title Wi-Fi signal strength'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Signal Quality'
	echo 'graph_category network'
	echo 'graph_scale yes'
	echo 'graph_printf %6.2lf'

	# Set Info.
	for (( Z = 0; Z < ${#LABEL[@]}; ++Z ))
	do
		echo "${LABEL[$Z]}.label ${LABEL[$Z]}"
		echo "${LABEL[$Z]}.draw LINE1"
		echo "${LABEL[$Z]}.warning ${WARN_RES}"
		echo "${LABEL[$Z]}.critical ${CRITICAL_RES}"
		echo "${LABEL[$Z]}.info Signal Strength"
	done

	exit 0
fi

for (( Z = 0; Z < ${#LABEL[@]}; ++Z ))
do
	echo "${LABEL[$Z]}.value ${SIGNAL[$Z]}"
done

